apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  WELCOME: "Hello from ConfigMap (wave 0)"# retrigger Sat Sep 20 11:16:04     2025
